# Generated by Django 4.1.13 on 2024-03-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_owners_alter_pet_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pet',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owners',
            field=models.ManyToManyField(blank=True, to='pets.owner'),
        ),
    ]
