# Generated by Django 4.1.13 on 2024-03-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_pet_unique_together_alter_pet_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=150),
        ),
    ]
