# Generated by Django 4.1.13 on 2024-06-10 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_pet_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='contact',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='address',
        ),
    ]
